#
#  SPDX-License-Identifier: Apache-2.0
#
#  Copyright The original authors
#
#  Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

project.version=${project.version}
quarkus.banner.enabled=false
quarkus.package.output-name=hardwood
quarkus.package.runner-suffix=-cli
quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:25.0.2.0-Final-java25
quarkus.native.additional-build-args=-march=compatibility,--gc=serial,-J--enable-native-access=ALL-UNNAMED,--initialize-at-run-time=org.apache.logging.log4j.core.config.yaml.YamlConfiguration
%prod.quarkus.log.level=ERROR
%test.quarkus.log.level=ERROR
